@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 12 01:58:39 -0400 2025
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim FFT_to_GPIO_wrapper_behav -key {Behavioral:sim_1:Functional:FFT_to_GPIO_wrapper} -tclbatch FFT_to_GPIO_wrapper.tcl -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/FFT_Test.protoinst" -protoinst "protoinst_files/FFT_to_GPIO.protoinst" -view C:/Xilinx/Projects/DRC_Rev2.0_Deliverables/Vivado2023.1/DRC_Rev2.0_FW/FFT_Test_wrapper_behav.wcfg -log simulate.log"
call xsim  FFT_to_GPIO_wrapper_behav -key {Behavioral:sim_1:Functional:FFT_to_GPIO_wrapper} -tclbatch FFT_to_GPIO_wrapper.tcl -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/FFT_Test.protoinst" -protoinst "protoinst_files/FFT_to_GPIO.protoinst" -view C:/Xilinx/Projects/DRC_Rev2.0_Deliverables/Vivado2023.1/DRC_Rev2.0_FW/FFT_Test_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
