# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/NYorr/Downloads/project_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0.xci
# IP: The module: 'design_1_util_ds_buf_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/NYorr/Downloads/project_1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_6_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/NYorr/Downloads/project_1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/NYorr/Downloads/project_1/project_1/project_1.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0.xci
# IP: The module: 'design_1_util_ds_buf_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/NYorr/Downloads/project_1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/NYorr/Downloads/project_1/project_1/project_1.gen/sources_1/bd/design_1/ip/design_1_util_ds_buf_6_0/design_1_util_ds_buf_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_util_ds_buf_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
